### ISSUE TITLE
The model [App\User] does not support soft deleting.

### ISSUE THREAD

**Issue by fishnux** [spinen/laravel-garbage-man#21]
```
The model [App\User] does not support soft deleting.
```
https://github.com/spinen/laravel-garbage-man/blob/0bfed10e052f8659cab8dd9fdab4863ce70c081e/src/Commands/PurgeCommand.php#L169

Soft-deleting is enabled for this model. forceDelete() exists, but onlyTrashed() doesn't:
https://github.com/laravel/framework/blob/9b10dcb31f1cc81322f9ec193aea0a8ba9e6db88/src/Illuminate/Database/Eloquent/SoftDeletes.php#L29
(Laravel 5.5)

Perhaps we could delete this check?
```
!method_exists($model, 'onlyTrashed')
```
P.S.: I would do a pull request, but I'm not familiar with PHP packages.

**Comment by fishnux** [comment]
I've created a pull request after I've verified my theory. I created the following dummy method in App\User:
```
public function onlyTrashed() {
        return "dummy";
}
```
Garbageman worked without errors after that :)

**Comment by jimmypuckett** [comment]
@fishnux Thanks so much for giving back to the project!  Let me look over what you have going on & get back with you.

**Comment by jimmypuckett** [comment]
@fishnux Can you post up the `App\User` model that you were working with that gave you this error?

**Comment by fishnux** [comment]
Hi @jimmypuckett, here:
https://gist.github.com/fishnux/cd20ec2319f84ac198b2adab0ad11efc

**Comment by jimmypuckett** [comment]
What version of Laravel are you using?

**Comment by fishnux** [comment]
Laravel v5.5.32

**Comment by jimmypuckett** [comment]
That is interesting as the macro is defined...

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/SoftDeletingScope.php#L122

I will do a little more digging...

**Comment by jimmypuckett** [comment]
OK, @fishnux, I am confused.  I am not exactly sure why we are doing the `if (!method_exists($model, 'onlyTrashed') || !method_exists($model, 'forceDelete')) {` as the `onlyTrashed` is a macro & not a method, so that is not a good check to make sure that `SoftDelete` is enabled.

As you see later in the method, we call...

```php
        $query = $this->laravel->make($model)
                               ->where('deleted_at', '<', $expiration)
                               ->onlyTrashed();
```

so we have to ensure hat the `onlyTrashed` & `forceDelete` is available incase someone accidentally running the command on a model without `SoftDelete`.

I am not sure why you are getting an error, but I would like to rework this method to do better checks.  There is a method called `class_uses` that will return an array of traits.  I would like to rework this check to make sure that the trait is on the model.

Can we fix it this weekend or is it blocking you right now?

**Comment by jimmypuckett** [comment]
OK, I have chased this down & it appears that it was a change in laravel 5.2 that never got caught where the `onlyTrashed` method was removed to only be the macro.

**Comment by fishnux** [comment]
Thanks for taking a look into this issue! Feel free to fix it on the weekend, I'm currently using the workaround I discovered:
```
public function onlyTrashed() {
        return "dummy";
}
```

**Comment by ssfinney** [comment]
@jimmypuckett Can we address/close this issue for the new version we are about to release?

**Comment by jimmypuckett** [comment]
Yes, now that we are making the 2.x line for Laravel >=5.5, then can can address the issue.
